# -*- coding: utf-8 -*-
"""assignment2ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKKad8PEl6N4n-C_AZ7nGnecGv6k9n85
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.preprocessing import KBinsDiscretizer

# Load the dataset
df = pd.read_csv('/AWCustomers.csv')

# Selected features
selected_features = [
    'BirthDate', 'Gender', 'MaritalStatus', 'Education', 'Occupation',
    'HomeOwnerFlag', 'NumberCarsOwned', 'TotalChildren', 'NumberChildrenAtHome',
    'CountryRegionName', 'YearlyIncome'
]
resultattribute = 'FirstName'
df = df[selected_features + [resultattribute]]

# Part 2
# (a) Handling Null Values
for col in df.columns:
    if df[col].isnull().sum() > 0:
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col].fillna(df[col].mean(), inplace=True)
        else:
            df[col].fillna(df[col].mode()[0], inplace=True)

# (b) Normalization (Min-Max Scaling)
scaler = MinMaxScaler()
numeric_cols = ['HomeOwnerFlag', 'NumberCarsOwned', 'TotalChildren', 'NumberChildrenAtHome', 'YearlyIncome']
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# (c) Standardization
standard_scaler = StandardScaler()
df[numeric_cols] = standard_scaler.fit_transform(df[numeric_cols])

# (d) One-Hot Encoding for Categorical Variables
categorical_cols = ['Gender', 'MaritalStatus', 'Education', 'Occupation', 'CountryRegionName']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# (e) Discretization (Binning) for Continuous Attribute 'YearlyIncome'
kbins = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
df['YearlyIncome_Binned'] = kbins.fit_transform(df[['YearlyIncome']])

print(df.head())
print(df.shape)

#part 3
from sklearn.model_selection import train_test_split


if 'BirthDate' in df.columns:
    df = df.drop(columns=['BirthDate'])


X = df.drop(columns=['FirstName'])
y = df['FirstName']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=None
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

